id: A6BCB029C
title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:26:24.160963
  last_modified_at: 2022-03-01 02:26:24.160970
